Emily dev
Jingyan95/TopLFV pull request #9
Opened 2023-10-08 08:07 UTC by emily-tsai11

This PR includes the changes to nano_files_2016.py, makeJobs.py, and submitJobs.py that are in Jack_dev.

2023-10-31 15:06 UTC, Jingyan95 reviewed
1st patch comments: I was able to run the code and produce histograms with out problem. The cutflow table script does not seem to work on lxplus. I will send you more comments as I read through changes made to MyAnalysis.cc and plotting scripts.

2023-10-31 15:06 UTC, Jingyan95 commented on README.md
> +python root -l -b -q Cutflow.cc
it does not look like I can run this command on lxplus..

2023-11-01 14:34 UTC, Jingyan95 commented on src/MyAnalysis.cc
> +  const std::vector<Double_t> ff_pt_bins = {20.0, 40.0, 60.0, 100.0, 220.0};
if it is matter of reading 2d histogram, I feel like it is not necessary to hard-encode binning information here? The binning scheme could change in your FF measurement code and we may forgot to update here.

2023-11-01 14:46 UTC, Jingyan95 commented on src/MyAnalysis.cc
> +      if (!Event->OnZ()) { // Region D
it seems like FF is only applied in three instances (labeled as Region D by you) . I think we make it more general, I would maybe try:
 - reduce the number of regions. you currently have 14 and this can be reduced to 10 or 9
 - for all the remaining regions, applied the same factor measured by the combined region (OnZ ee + OnZ mumu)
 - since you have this dIdx, you should make sure FF is only applied (e.g. weight_Event *= FFweight) when dIdx tells you tau fails the tight requirement

2023-11-01 18:20 UTC, Jingyan95 requested changes
My third and final patch of comments.

2023-11-01 18:20 UTC, Jingyan95 commented on plot/drawHists.py
> +                        h1 = Hists[numyear][f][numc][numch][numreg][numdom][numvar].Clone()
here I think you should 
 - ignore histograms from DY and ttbar
 - only append histogram from data to H1 when numdom = 1
 - append other histograms (other than DY and ttbar) from MC and data when numdom = 0

2023-11-01 18:20 UTC, Jingyan95 commented on plot/drawHists.py
> +                # Plots with no background estimation
I would call this pure MC-driven estimate. Also, I'd recommend to create two folders one to hold histograms using data-driven estimate (ABCD), the other hold histograms using pure MC-driven estimate. This makes it easier to tell what method is used to estimate fake tau estimate.

2023-11-01 18:20 UTC, Jingyan95 commented on plot/drawHists.py
> +            SummaryPlot(H, HSignal, SamplesNameStack, namereg, regionsName[numreg], namedom, domainsName[numdom], nameyear)
similarly for these summary plots, I would recommend to create two sets of them, one using ABCD method the other using pure MC

2023-11-02 13:03 UTC, emily-tsai11 commented on bin/nano_files_2016.py
yes, I copied the files from Jack_dev

2023-11-02 13:07 UTC, emily-tsai11 commented on bin/submitJobs.py
> +jobruntime = 14400 # 4 hrs
Most of the jobs finish in <10-20 minutes. There are a few jobs in particular that take >1 hour, so I set the runtime to 4 hours to make sure all the jobs finish.

2023-11-02 13:14 UTC, emily-tsai11 commented on src/main.cc
> +    auto workerSummary = t1.Loop(Form("test_%u.root", workerID), "mc", "TTTo2L2Nu", "2016", "", 88.4, 16.81, 125894, std::ref(progress), std::ref(counter));
125894 is the sum of all the GetEntries() for the four 2016_TTTo2L2Nu_UL root files, so it should be the number of events.

2023-11-02 13:15 UTC, emily-tsai11 commented on src/main.cc
> +    auto workerSummary = t1.Loop(Form("test_%u.root", workerID), "mc", "TTTo2L2Nu", "2016", "", 88.4, 16.81, 125894, std::ref(progress), std::ref(counter));
I switched to TTTo2L2Nu at some point for debugging purposes, but it doesn't matter which sample is used for testing.

2023-11-02 13:15 UTC, emily-tsai11 commented on README.md
> +python root -l -b -q Cutflow.cc
Fixed!

2023-11-02 13:17 UTC, emily-tsai11 commented on src/MyAnalysis.cc
> +  TFile *f_Ta_JetFF = new TFile("data/TAU/" + year + "_JetToTauFakeFactors.root");
Done

2024-06-25 18:56 UTC, Jingyan95 commented on README.md
> +git clone git@github.com:Jingyan95/TopLFV.git
can we do: git clone --recurse-submodules --remote-submodules ?
this should git clone the project and the most up-to-date module.

2024-06-25 18:56 UTC, Jingyan95 commented on README.md
> +. /cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/setup.sh
is the set up commend here consistent with what's in the condor jobs?

2024-06-25 18:57 UTC, Jingyan95 commented on README.md
> +python3 makeJobs.py
do we need to explicitly call python3 instead of just python?

2024-06-25 19:00 UTC, Jingyan95 commented on README.md
> +The log can still be checked in `CutFlowTables.log`. *NOTE: for some reason the table of contents only shows up after compiling twice with pdflatex.*
this is normal latex behavior as latex will collect content information in .toc the first time you compile and produce TOC the second time.

2024-06-25 19:02 UTC, Jingyan95 commented on README.md
> +TClass::Init:0: RuntimeWarning: no dictionary for class pair<edm::Hash<1>,edm::ParameterSetBlob> is available
yeah, these are infamous complaints by ROOT.. not sure how to fix them though..

2024-06-25 19:06 UTC, Jingyan95 commented on bin/submitJobs.py
> +            submit += 'batch_name = ' + key + '\n'
this batch name is handy!

2024-06-25 19:09 UTC, Jingyan95 commented on bin/makeJobs.py
> -cms = '/afs/cern.ch/work/j/jingyan/public/CMSSW_10_6_4/src/'
ok, nice! now we get rid of this weird CMSSW line

2024-06-25 19:10 UTC, Jingyan95 commented on bin/makeJobs.py
> +        'source /cvmfs/sft.cern.ch/lcg/views/LCG_104c/x86_64-el9-gcc13-opt/setup.sh\n' +\
please make sure to use the same setup

2024-06-25 19:10 UTC, Jingyan95 commented on bin/makeJobs.py
> +print('Runtime was %.2f seconds.' % (end - start))
it is all about runtime and performance

2024-06-25 19:19 UTC, Jingyan95 commented on hists/hadd.py
> +addedFilesTT = {"2016APV": [], "2016": [], "2017": [], "2018": []} # TT, WWTo2L2Nu
what's the motivation to group tt and WW? WW is strictly EWK process while tt is mostly QCD

2024-06-25 19:25 UTC, Jingyan95 commented on hists/hadd.py
> +addedFilesDY = {"2016APV": [], "2016": [], "2017": [], "2018": []} # DY, ZZTo2L2Nu
ok, I started to understand a bit. this basically tries to separate nonprompt background from VV category. I think maybe we create a separate category for these two... let's call it "Others". and we move the "Stat. Only" legend from the upper panel to the lower panel

2024-06-25 19:31 UTC, Jingyan95 commented on include/MyAnalysis.h
> +  typedef std::vector<Dim4_2> Dim5_2;
super picky question: would it possible to do a [alias template](https://en.cppreference.com/w/cpp/language/type_alias) for these vectors?

2024-06-25 19:33 UTC, Jingyan95 commented on postproc/latex/beamerposter.sty
what do we use this file for?

2024-06-25 19:44 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    CMS.SaveCanvas(canv, saveName + ".png", close=False)
do we need both png and pdf?

2024-06-25 19:49 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    frame = pad1.DrawFrame(x_min, 0.2, x_max, 6000*y_max)
it seems like this is the only function that uses "frame" is there way to move alway from it here?

2024-06-25 19:50 UTC, Jingyan95 commented on postproc/plotFunctions.py
a lot cleaner than my implementation

2024-06-25 19:58 UTC, Jingyan95 commented on src/MyAnalysis.cc
> +  const std::map<TString, std::vector<float>> vars2D = {
if the 2D histograms are only used for fake factor measurement. I recommend move them to a feature branch rather than merge them to the main branch

2024-06-25 20:03 UTC, Jingyan95 commented on postproc/jetToTauFakeFactors.py
I recommend this script to go to a feature branch

2024-06-25 20:10 UTC, Jingyan95 commented on src/MyAnalysis.cc
> +      if ((int) Tau_idDeepTau2017v2p1VSjet[l] < 1 || (int) Tau_idDeepTau2017v2p1VSe[l] < 2 || (int) Tau_idDeepTau2017v2p1VSmu[l] < 8) continue;
can we add a note here on loose and tight tau definition? (i.e. VSjet WP)

2024-06-25 20:21 UTC, Jingyan95 commented on src/MyAnalysis.cc
> +    tauPt = Event->ta1()->pt_;
the tauPt and tauEta lines feel a bit out of place as they are the only two variables that get updated. could we move them inside the histogram loop?

2024-06-25 22:54 UTC, Jingyan95 commented on postproc/common.py
> +import cmsstyle as CMS
it only works for if I change it to 
import cmsstyle.src.cmsstyle

2024-06-25 23:17 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    y_max = hists[0].GetMaximum()
suggest to set some minimum values for this y_max to prevent y_max = y_min

2024-06-26 00:45 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    y_max = hists[0].GetMaximum()
also recommend to set an absolute minimum for y_min (e.g. 0.01)

2024-06-26 01:11 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    frame.Draw("AXISSAMEY+")
these axis draws should also be applied to non-summary histograms. otherwise axis ticks will be covered by bins. e.g.
<img width="841" alt="Screenshot 2024-06-25 at 21 10 16" src="https://github.com/Jingyan95/TopLFV/assets/43122048/ea050141-92ab-4f3d-b18f-d84457a0b7d4">

2024-06-26 01:13 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +def plotSummary(hists, SignalHists, Fnames, year, iRegion, region, iDomain, saveDir):
need some adjustment to the top margin
<img width="858" alt="Screenshot 2024-06-25 at 21 12 29" src="https://github.com/Jingyan95/TopLFV/assets/43122048/f6ee50f4-ac33-41de-8cad-a64b74a8fef9">

2024-06-26 01:17 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +def plot1DStack(hists, year, charge, iChannel, iRegion, varName, var, topLabel, saveDir):
title offset for the lower panel x-axis need some adjustment 
<img width="871" alt="Screenshot 2024-06-25 at 21 16 23" src="https://github.com/Jingyan95/TopLFV/assets/43122048/02fef46c-0863-4001-ba4b-91c5f45f8b68">

2024-06-26 01:32 UTC, Jingyan95 reviewed
Overall I am happy with the code quality improvement. I submitted some comments for some of the files (mostly minor suggestions). The only general suggestion I have is to reduce the volume of code/output histograms at this stage. This can be done via:
 - Not saving 2D histograms
 - Reducing the number of regions
 - Reducing the number of variables
 - Not plotting histograms with one loose but not tight tau. In principle, the main branch should only do the "application" (i.e. data-driven estimate with these histograms) instead of running the plot1DStack function on these histograms. 
 - Not plotting 2D histograms

2024-06-26 07:52 UTC, emily-tsai11 commented on README.md
> +python3 makeJobs.py
this is probably left over from when "python" still called python2 instead of 3. fixed!

2024-06-26 07:52 UTC, emily-tsai11 commented on README.md
> +. /cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/setup.sh
yep! also see your comment below

2024-06-26 07:55 UTC, emily-tsai11 commented on README.md
> +The log can still be checked in `CutFlowTables.log`. *NOTE: for some reason the table of contents only shows up after compiling twice with pdflatex.*
added to README

2024-06-26 07:58 UTC, emily-tsai11 commented on bin/makeJobs.py
> +        'source /cvmfs/sft.cern.ch/lcg/views/LCG_104c/x86_64-el9-gcc13-opt/setup.sh\n' +\
fixed

2024-06-26 07:59 UTC, emily-tsai11 commented on bin/makeJobs.py
> +print('Runtime was %.2f seconds.' % (end - start))
more like I wanted to know how long I had to wait haha

2024-06-26 08:00 UTC, emily-tsai11 commented on postproc/latex/beamerposter.sty
it's used for compiling with pdflatex. I added this in when pdflatex complained about missing this file.

2024-06-26 08:15 UTC, emily-tsai11 commented on README.md
> +git clone git@github.com:Jingyan95/TopLFV.git
done

2024-06-26 08:16 UTC, emily-tsai11 commented on postproc/common.py
> +import cmsstyle as CMS
done

2024-06-26 08:49 UTC, emily-tsai11 commented on src/MyAnalysis.cc
> +      if ((int) Tau_idDeepTau2017v2p1VSjet[l] < 1 || (int) Tau_idDeepTau2017v2p1VSe[l] < 2 || (int) Tau_idDeepTau2017v2p1VSmu[l] < 8) continue;
done

2024-06-26 08:53 UTC, emily-tsai11 commented on src/MyAnalysis.cc
> +    tauPt = Event->ta1()->pt_;
done

2024-06-26 09:12 UTC, emily-tsai11 commented on include/MyAnalysis.h
> +  typedef std::vector<Dim4_2> Dim5_2;
done!

2024-06-26 19:45 UTC, Jingyan95 commented on README.md
> +python3 makeJobs.py
> this is probably left over from when "python" still called python2 instead of 3. fixed!

"python" does not seem to work with ./setup.sh command for some reason. for now let's maybe revert back to the full setup commend or python3. up to you!

2024-06-26 20:58 UTC, Jingyan95 commented on README.md
> +./setup.sh
I tried various things and the following combination works for me.
put 

source /cvmfs/sft.cern.ch/lcg/views/LCG_106/x86_64-el9-gcc13-opt/setup.sh

in setup.sh

and run

source setup.sh

2024-06-26 22:13 UTC, emily-tsai11 commented on README.md
> +./setup.sh
done

2024-07-05 16:58 UTC, Jingyan95 commented on postproc/plotFunctions.py
> +    for iHist, loopHist in enumerate(reversed(MCHists)):
urgent request: the use of reversed histograms when filling legend entry seems to be a bug because the sample name list is not reversed accordingly. Suggest to remove the "reversed()" on this line.

2024-09-04 01:41 UTC, Jingyan95 commented
closing this PR as we decided to move to 3D matrix method

2024-09-04 01:41 UTC, closed without merging